module.exports = {
  attributes: {
    auth: ['id', 'name', 'email'],
    inventory: ['id', 'sku', 'quantity', 'color', 'size', 'cost_cents', 'price_cents'],
    inventory_products: ['id', 'product_name'],
    orders: ['id', 'name', 'email', 'order_status', 'total_cents', 'transaction_id', 'shipper_name', 'tracking_number'],
    order_product_inventory: ['color', 'size'],
    order_products: ['id', 'product_name'],
  },
  styles: [
    'Girl next door',
    'Sports Wear',
    'Preppy',
    'Punk',
    'Flamboyant',
    'Vacation',
    'Boho/Bohemian chic',
    'Hip Hop',
    'Geeky chic',
    'Streetwear',
    'Casual Chic',
    'Lagenlook',
    'Cowgirl',
    'Maternity',
    'Modest',
    'Artsy',
    'Formal Office Wear',
    'Rocker Chic',
    'Scene',
    'Ankara',
    'Tomboy',
    'Military',
    'Cosplay',
    'Retro',
    'Psychedelic',
    'Rave',
    'Garconne look',
    'Haute Couture',
    'Goth',
    'Evening Black Tie',
    'Flapper',
    'Kawai',
    'Business Casual',
    'Girly',
    'Grunge',
    'Skateboarders',
    'p1 style',
  ],
  brands: [
    'Acne Studios',
    'adidas',
    'adidas Originals',
    'Adrianna Papell',
    'Aerosoles',
    'AG - Adriano Goldschmied',
    'Akris',
    'Alberta Ferretti',
    'Aldo',
    'Alex Evenings',
    'Alexander McQueen',
    'Alexander Wang',
    'Alice & Olivia',
    'Alo Yoga',
    'Alternative',
    'Altuzarra',
    'Amanda Uprichard',
    'Amazon Collection',
    'Amazon Essentials',
    'Amiri',
    'Andrew Marc',
    'ANN TAYLOR',
    'Anne Cole',
    'Anne Klein',
    'Anthropologie',
    'Anuschka',
    'Aquatalia',
    'Aquazzura',
    'Ariat',
    'Armani',
    'Asos',
    'Asos Curve',
    'Asos Petite',
    'Asos Tall',
    'ASTR the Label',
    'ATM Anthony Thomas Melillo',
    'A|X Armani Exchange',
    'Badgley Mischka',
    'Baffin',
    'Baggallini',
    'Bailey',
    'Bailey 44',
    'Balenciaga',
    'Bali Intimates',
    'Bally',
    'Balmain',
    'Bandolino',
    'Barneys New York',
    'BB Dakota',
    'BCBGeneration',
    'Bcbgmaxazria',
    'Bella Vita',
    'Ben Sherman',
    'Bershka',
    'Betsey Johnson',
    'Billabong',
    'Black Halo',
    'Blank NYC',
    'Bleu Rod Beattie',
    'Blizzard Bay',
    'Blondo',
    'Bodyglove',
    'Bottega Veneta',
    'Brandon Maxwell',
    'Brave Soul',
    'Brinley Co',
    'Brioni',
    'Brixton',
    'Brunello Cucinelli',
    'Buckle Down',
    'Buffalo David Bitton',
    'Bugatchi',
    'Burberry',
    'Buxton',
    'C-IN²',
    'Calvin Klein',
    'CALVIN KLEIN 205W39NYC',
    'Calvin Klein Underwear',
    'Canada Goose',
    'Capezio',
    'Carhartt Work in Progress',
    'Carlos By Carlos Santana',
    'Carmen Marc Valvo',
    'Carolina Herrera',
    'CAT',
    'Champion',
    'Chantelle',
    'Chaps',
    'Charles by Charles David',
    'Charles River Apparel',
    'Chinese Laundry',
    'Chloé',
    'Christian Louboutin',
    'Cinch',
    'Cinq à Sept',
    'Clarks',
    'Clementine',
    'Clementine Apparel',
    'Coastal Blue',
    'Cole Haan',
    'Columbia',
    'Comme Des Garçons',
    'Contemporaine',
    'Core 10',
    'Corso Como',
    'Cosabella',
    'Crocs',
    'Cuba Vera',
    'Cult Gaia',
    'cupcakes and cashmere',
    'Current Elliott',
    'Daily Ritual',
    'Danner',
    'Danskin',
    'Dansko',
    'Davidor',
    'DC',
    'Dearfoams',
    'Deer Stags',
    'Delpozo',
    'Democracy',
    'Derek Lam',
    'Derek Rose',
    'Desigual',
    'Diane Von Fürstenberg',
    'Dickies',
    'Diesel',
    'Dior',
    'Disney',
    'Djab',
    'DKNY',
    'DL1961',
    'Dockers',
    'Dolce & Gabbana',
    'Dolce Vita',
    'Donald J Pliner',
    'Dondup',
    'Donna Morgan',
    'Dr. Martens',
    'Dr. Scholls',
    'dRA',
    'Dress The Population',
    'Dries Van Noten',
    'Dsquared2',
    'Dundas',
    'Dunham',
    'Duofold by Champion',
    'Durango',
    'DVS',
    'E. Marinella',
    'Eastland',
    'Easy Spirit',
    'Easy Street',
    'Eberjey',
    'Ecco',
    'Echo Design',
    'Ecko',
    'Ed Ellen Degeneres',
    'Edie Parker',
    'EF Collection',
    'Eidon',
    'Eidos',
    'El Naturalista',
    'Element',
    'Eleventy',
    'Elie Tahari',
    'Elisabetta Franchi',
    'Eliza J',
    'Ella Moon',
    'Ella Moss',
    'Ellen Tracy',
    'Ellie Shoes',
    'Elomi',
    'Emerica',
    'Emilia Wickstead',
    'Emilio Pucci',
    'Emporio Armani',
    'English Laundry',
    'Enza Costa',
    'Equipment',
    'Erdem',
    'Eres',
    'Ermenegildo Zegna',
    'Escante',
    'Eskandar',
    'Etnies',
    'Etro',
    'Fabiana Filippi',
    'Fabrizio Viti',
    'Faith Connexion',
    'Faithfull The Brand',
    'Falke',
    'Fantasie',
    'Farah',
    'Fashion Union',
    'Fay',
    'Fea',
    'Fear of God',
    'Felina',
    'Fendi',
    'Fergalicious',
    'Figue',
    'Fila',
    'Finders Keepers',
    'FitFlop',
    'FiveSeventyFive',
    'Fleur du Mal',
    'Florsheim',
    'FLY London',
    'Foley Corinna',
    'For Love & Lemons',
    'Forplay',
    'Fossil',
    'Foster Grant',
    'Fox',
    'Foxcroft',
    'Frame Denim',
    'Franco Sarto',
    'Fred Perry',
    'Freddy',
    'Free People',
    'French Connection',
    'Freya',
    'Fruit Of The Loom',
    'Frye',
    'G-Star',
    'G.H. Bass & Co.',
    'Gabby Skye',
    'Gabriela Hearst',
    'Galvan',
    'Ganni',
    'GANT',
    'Garrett Leight',
    'GBX',
    'GCDS',
    'Gentle Souls',
    'Geoffrey Beene',
    'Georgia Boot',
    'Geox',
    'Giambattista Valli',
    'Gianni Feraud',
    'Gianvito Rossi',
    'Gildan',
    'Giorgio Armani',
    'Giorgio Brutini',
    'Giuseppe Zanotti',
    'Givenchy',
    'Glamorise',
    'Globe',
    'Gloria Vanderbilt',
    'Goddess',
    'Gold Toe',
    'Golden Goose',
    'Goodthreads',
    'Goorin Brothers',
    'Gordon Rush',
    'Gorjana',
    'Gossard',
    'Gottex',
    'Grasshoppers',
    'Green Dragon',
    'GRLFRND',
    'Gucci',
    'h:ours',
    'Haflinger',
    'Haggar',
    'Haider Ackermann',
    'Halston Heritage',
    'Hanes',
    'Hanky Panky',
    'Hanro',
    'Harris',
    'Harry Brown',
    'Hart Schaffner Marx',
    'Hartford',
    'Hat Attack',
    'Haute Hippie',
    'Havaianas',
    'Hawke & Co',
    'Hayward',
    'Head',
    'Heart & Dagger',
    'Heidi Klein',
    'Heidi Klum Intimates',
    'Helly Hansen',
    'Helmut Lang',
    'Henschel',
    'Herno',
    'Herschel',
    'Hi-Tec',
    'Hiltl',
    'Hobie',
    'Hogan',
    'Honeydew Intimates',
    'Hot Sox',
    'House Of Harlow',
    'HPC Trading Co.',
    'Hudson',
    'Hue',
    'HUF',
    'HUGO BOSS',
    'I.AM.GIA',
    'I.D. Sarrieri',
    'I.FIV5',
    'Ichi',
    'iCollection',
    'Icone',
    'ICONS',
    'Ienki Ienki',
    'Ignite',
    'Ih Nom Uh Nit',
    'Ike Behar',
    'IL BISONTE',
    'Ileana Makri',
    'Illesteva',
    'Ilse Jacobsen',
    'Imagine Skateboards',
    'Imagine Vince Camuto',
    'Incotex',
    'Indah',
    'Indigo Rd.',
    'Influence',
    'Influence Plus',
    'Ingrid & Isabel',
    'Inis Meáin',
    'Inov-8',
    'Ipanema',
    'Iphoria',
    'Ippolita',
    'Iris & Lilly',
    'Irish Setter',
    'Iro',
    'Isaac Mizrahi New York',
    'Isabel Marant',
    'Isaia',
    'Isotoner',
    'Issey Miyake',
    'Italian Finest Jewelry',
    'Ivanka Trump',
    'J Brand',
    'J Kara',
    'J.crew',
    'J.Lindeberg',
    'J.O.A.',
    'J.W.Anderson',
    'J/Slides',
    'Jack & Jones',
    'Jack Adams',
    'Jack Rogers',
    'Jacquemus',
    'Jag Jeans',
    'Jambu',
    'James Jeans',
    'James Perse',
    'Jason Wu',
    'Jeffrey Campbell',
    'Jenny Yoo',
    'Jessica Howard',
    'Jessica Simpson',
    'Jil Sander',
    'Jill Stuart',
    'Jimmy Choo London',
    'Jockey',
    'Joe Boxer',
    'Joe\'s',
    'Johanna Ortiz',
    'John Elliott Co',
    'John Varvatos',
    'Joie',
    'Jonathan Simkhai',
    'Jones New York',
    'Josef Seibel',
    'Joseph',
    'Joules',
    'Juan Carlos Obando',
    'Julian Taylor',
    'Junarose',
    'K. Bell Socks',
    'K.Jacques',
    'Kaanas',
    'kamik',
    'Kangol',
    'Kanu Surf',
    'Kappa',
    'Karen Kane',
    'Karen Neuburger',
    'Karen Walker',
    'Karl Lagerfeld',
    'Karla Colletto',
    'Kasper',
    'Kate Spade New York',
    'Katy Perry',
    'Kayu',
    'Keds',
    'Keen',
    'Keepsake the Label',
    'Kelsi Dagger',
    'Kendall Kylie',
    'Kenneth Cole',
    'Kenneth Cole Reaction',
    'Kenneth Jay Lane',
    'Kensie',
    'Key Apparel',
    'Khaite',
    'Kiki De Montparnasse',
    'Kingsley Ryan',
    'Kipling',
    'Kisuii',
    'Kiton',
    'Kobi Halperin',
    'Koché',
    'Kodiak',
    'Koi',
    'Koral',
    'Ksubi',
    'L\'Academie',
    'L\'agence',
    'La Blanca',
    'La Made',
    'La Perla',
    'La Petite Robe Di Chiara Boni',
    'Lacoste',
    'Lafayette 148 New York',
    'Lana Jewelry',
    'Lanvin',
    'Lark & Ro',
    'Le 31',
    'Le Mystere',
    'Lee',
    'Leg Avenue',
    'LeSportsac',
    'Levi\'s',
    'Life Stride',
    'LIKELY',
    'Lilly Pulitzer',
    'Liquid Blue',
    'Lisa Marie Fernandez',
    'Lisa Perry',
    'Loeffler Randall',
    'Loewe',
    'London Fog',
    'London Times',
    'Loro Piana',
    'Louis Raphael',
    'Louise et Cie',
    'Love Moschino',
    'Lovers Friends',
    'LoveShackFancy',
    'LPA',
    'Lucky Brand',
    'Lugz',
    'Luli Fama',
    'Lupo',
    'Maaji',
    'Madden Girl',
    'Maggy London',
    'Maidenform',
    'Maison Margiela',
    'Majorelle London',
    'Manolo Blahnik',
    'Mara Hoffman',
    'Marc Jacobs',
    'Marcelo Burlon',
    'Margaritaville',
    'Marina Rossini',
    'Marni',
    'MARVEL',
    'Maurices',
    'Max Mara',
    'Maxine Of Hollywood',
    'McQ by Alexander McQueen',
    'Mephisto',
    'Merrell',
    'Michael Antonio',
    'Michael Kors',
    'Michael Stars',
    'Miiyu',
    'Milly',
    'Minkpink',
    'Miss Selfridge',
    'Missoni',
    'Miu Miu',
    'Miz Mooz',
    'Mizuno',
    'Moncler',
    'Monrow',
    'Moschino',
    'Mother',
    'Msgm',
    'MSK',
    'Muk Luks',
    'N:Philanthropy',
    'Naeem Khan',
    'Naked & Famous Denim',
    'Nancy Gonzalez',
    'Nanette Lepore',
    'Nanushka',
    'Naot',
    'Narciso Rodriguez',
    'Natori',
    'Naturalizer',
    'Nautica',
    'NBD',
    'Neff',
    'Neil Barrett',
    'Neon Buddha',
    'New Balance',
    'New Look',
    'Next',
    'Nicholas Kirkwood',
    'Nick Graham',
    'Nicole Miller',
    'Nike',
    'Nili Lotan',
    'Nina',
    'Nine West',
    'No Nonsense',
    'Noak',
    'Nocona Belt Co.',
    'Noisy May',
    'Norma Kamali',
    'Northside',
    'Not Rated',
    'Novica',
    'NSF',
    'Nudie Jeans',
    'Nunn Bush',
    'NY Collection',
    'N°21',
    'O\'Neill',
    'Oakley',
    'OAMC',
    'Oasis',
    'Obey',
    'Off-white',
    'Officine Creative',
    'Officine Générale',
    'Old Friend Footwear',
    'Olive Oak',
    'Oliver Peoples',
    'Oliver Spencer',
    'Olivia Burton',
    'Olivia Von Halle',
    'Olymp',
    'On The Island',
    'OndadeMar',
    'One Teaspoon',
    'Oneworld',
    'OnGossamer',
    'Onia',
    'Only',
    'Only & Sons',
    'Only Hearts',
    'Onyx',
    'Onzie',
    'Opening Ceremony',
    'Orciani',
    'Original Penguin',
    'Orlebar Brown',
    'Oscar De La Renta',
    'Osiris',
    'Osman',
    'Our Legacy',
    'Ovadia & Sons',
    'OVERCOME',
    'Oye Swimwear',
    'p1',
    'Paco Rabanne',
    'Paige',
    'Pajar',
    'Palm Angels',
    'Panache',
    'Pancaldi',
    'Pantaloni Torino',
    'Paris Sunday',
    'Parker',
    'Patagonia',
    'Patrizia Pepe',
    'PAUL ANDREW',
    'Paul Smith',
    'Peepers',
    'Pendleton',
    'Perry Ellis',
    'PGA TOUR',
    'Philosophy di Lorenzo Serafini',
    'PIATTELLI',
    'Pieces',
    'Pierre Hardy',
    'PilyQ',
    'Pinko',
    'Pj Harlow',
    'PJ Salvage',
    'Playtex',
    'Polaroid',
    'Polo Ralph Lauren',
    'Prabal Gurung',
    'Prada',
    'Prettylittlething',
    'Privacy Please',
    'Proenza Schouler',
    'Propét',
    'Prps',
    'PT01',
    'Pull & Bear',
    'Puma',
    'Qed London',
    'Quartz Co.',
    'Quay Eyeware',
    'Queen Bee',
    'Quiksilver',
    'Quintsoul',
    'Quoddy',
    'Qupid',
    'R',
    'R&M Richards',
    'R13',
    'Rachel Roy',
    'Rachel Zoe',
    'Rafaella',
    'Rag & Bone',
    'Rails',
    'Ralph Lauren',
    'Ralph Lauren Purple Label',
    'Rampage',
    'Ramy Brook',
    'Raquel Allegra',
    'Ray-Ban',
    'Raye',
    'Re/Done',
    'Rebecca Minkoff',
    'Rebecca Taylor',
    'Red Kap',
    'Reebok',
    'Relic',
    'Report',
    'Revo',
    'Reyn Spooner',
    'Rhonda Shear',
    'Rick Owens',
    'Riders by Lee Indigo',
    'Rip Curl',
    'Robert Graham',
    'Robert Rodriguez',
    'Rocawear',
    'Rockport',
    'Rocky',
    'Roper',
    'Roxy',
    'Rta',
    'Ruby Rd.',
    'Russell Athletic',
    'Rvca',
    'S.L. Fashions',
    'Saint Laurent',
    'Salvatore Ferragamo',
    'Sanctuary',
    'Sandra Darren',
    'Saucony',
    'Schutz',
    'Seafolly',
    'See By Chloé',
    'Selected',
    'Shelli Segal',
    'Shoshanna',
    'Sies Marjan',
    'Silver Jeans Co',
    'Simone Pérèle',
    'Simons',
    'Skechers',
    'Skin',
    'Soffe',
    'Softwalk',
    'Sole Society',
    'Solid & Striped',
    'Soludos',
    'Sorel',
    'Southpole',
    'Sperry Top-Sider',
    'Splendid',
    'Spring Step',
    'Stacy Adams',
    'Star Vixen',
    'Starter',
    'Stella McCartney',
    'Steve Madden',
    'Stuart Weitzman',
    'Sunsets',
    'Superdown',
    'Superga',
    'Swim Systems',
    'T Alexander Wang',
    'T Tahari',
    'Tabitha Simmons',
    'Tadashi Shoji',
    'Tamara Mellon',
    'Taryn Rose',
    'Taylor Dresses',
    'Ted Baker',
    'Terez',
    'Teva',
    'The Fix',
    'The Mountain',
    'The North Face',
    'The Original Muck Boot Company',
    'The Row',
    'The Sak',
    'Theory',
    'Thom Browne',
    'Thomas Sabo',
    'Thorlos',
    'Three Dots',
    'Tibi',
    'Timberland',
    'Tod\'s',
    'Tom Ford',
    'Tommy Bahama',
    'Tommy Hilfiger',
    'Toms',
    'Tory Burch',
    'Tretorn',
    'Trevco',
    'Tribal',
    'Trina Turk',
    'Trotters',
    'True Religion',
    'Tularosa',
    'Tumi',
    'Twik',
    'U.P.W.W.',
    'U.S.Polo Association',
    'UGG',
    'Ugo Cacciatori',
    'Ulla Johnson',
    'Ultimo',
    'Ultracor',
    'Uman',
    'Umbro',
    'Uncivilised',
    'Unconditional',
    'Under Armour',
    'Undercover',
    'Underella by Ella Moss',
    'Undies.com',
    'Undiz',
    'Unfortunate Portrait',
    'Uniform Wares',
    'Unionbay',
    'Unique Vintage',
    'Unique21',
    'Unique21 Hero',
    'United Nude',
    'United Standard',
    'Universal Works',
    'Unlisted by Kenneth Cole',
    'Unravel',
    'Unsimply Stitched',
    'Uomolebole',
    'Ur',
    'Urban Code',
    'Urban Originals',
    'Urban Republic',
    'Urban Threads',
    'Urban Zen',
    'Urge',
    'Uttam Boutique Petite',
    'Uttam Boutique Plus',
    'Vaara',
    'Valentino',
    'Valextra',
    'Van Heusen',
    'Vanity Fair',
    'Vans',
    'Varley',
    'Vasque',
    'VASSARETTE',
    'Veja',
    'Velvet',
    'Vera Bradley',
    'Vera Wang',
    'Verandah',
    'Vero Moda',
    'Veronica Beard',
    'Versace',
    'Versus',
    'Very Volatile',
    'VETEMENTS',
    'Via Spiga',
    'Vibram Fivefingers',
    'Victoria Beckham',
    'Vigoss',
    'Vila',
    'Vilebrequin',
    'Vimmia',
    'Vince',
    'Vince Camuto',
    'Vintage 1946',
    'Vis à Vis',
    'Visvim',
    'Vitamin A',
    'Vivetta',
    'Vivienne Westwood',
    'Vix',
    'Vogue',
    'Volatile',
    'W. Kleinberg',
    'Wacoal',
    'WALK LONDON',
    'Walking Cradles',
    'Wallflower Jeans',
    'Walls',
    'Walter De Silva',
    'Wandler',
    'Want Les Essentiels',
    'Warm',
    'Warner\'s',
    'Warren Lotas',
    'We are Leone',
    'Weatherproof',
    'Weatherproof Vintage',
    'Weekday',
    'Weekend by Max Mara',
    'Wembley',
    'Wesc',
    'Western Chief',
    'What Goes Around Comes Around',
    'White Mountain',
    'White Warren',
    'Wigwam',
    'Wildfox',
    'William Rast',
    'Williams Cashmere',
    'Wilt',
    'With Love Darling',
    'Wolf & Whistle',
    'Wolford',
    'Wolverine',
    'Won Hundred',
    'Wonderbra',
    'Woolrich',
    'Wooyoungmi',
    'Wrangler',
    'WT02',
    'X by NBD',
    'X-Ray',
    'Xacus',
    'Xander Zhou',
    'Xcvi',
    'Ximena Kavalekas',
    'Xirena',
    'xoxo',
    'Xscape',
    'Xti',
    'Y',
    'Y / Project',
    'Y.A.S',
    'Y.A.S.',
    'Y.A.S. Tall',
    'Yang Li',
    'Yasmine Eslami',
    'Yeah Right NYC',
    'YEAR OF OURS',
    'Yeezy by Kanye West',
    'Yellow Box',
    'Yeprem',
    'YESTADT MILLINERY',
    'Yi Collection',
    'Yigal AzrouËl',
    'Ymc You Must Create',
    'YMI',
    'YOANA BARASCHI',
    'Yohji Yamamoto',
    'Yoki',
    'Yoki Fashion',
    'Yosi Samra',
    'You As',
    'Young Fabulous & Broke',
    'Young Frankk',
    'Yours Clothing',
    'Yuketen',
    'Yuliya Magdych',
    'Yumi',
    'Yumi Kim',
    'Yumi Petite',
    'Yumi Plus',
    'Yummie Tummie',
    'Yuul Yie',
    'Yuzefi',
    'Yves Saint Laurent Beauty',
    'Yves Salomon',
    'Yves Salomon - Army',
    'Yvonne Léon',
    'Z Supply',
    'Z. Cavaricci',
    'Zac Posen',
    'Zadig & Voltaire',
    'ZAG Bijoux',
    'Zancan',
    'Zanchetti',
    'Zanella',
    'Zanellato',
    'Zanerobe',
    'Zanone',
    'Zanzara',
    'Zaxy',
    'Zayan The Label',
    'Zenith',
    'Zero Maria Cornejo',
    'zeroUV',
    'ZeroXposur',
    'Zeus Dione',
    'Zeynep Arcay',
    'Zibi London',
    'Ziggy Chen',
    'Zigi Soho',
    'Ziginy',
    'Zign Shoes',
    'Ziio Jewellery',
    'Zimmerli',
    'Zimmermann',
    'Zobha',
    'Zoe Karssen',
    'Zoo York',
    'Zoot',
    'Zubaz',
  ],
  type: [
    'clothing'
  ]
}
